language: julia
sudo: false
julia:
    - 0.6
    - nightly
notifications:
    email: false
#script: # use the default script setting which is equivalent to the following
after_success:
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("Matching")); include(joinpath("docs", "make.jl"))'
    - julia -e 'cd(Pkg.dir("Matching")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
